import { useState } from 'react';
import { api } from '../../lib/catalog-client';
import type { ShopSettings, Extra } from '../../lib/catalog-types';
import { errorMessage, type AdminData } from './AdminApp';

export default function AdminSettings({ data, onSaved }: { data: AdminData; onSaved: () => Promise<void> }) {
  const [settings, setSettings] = useState(structuredClone(data.settings));
  const [extras, setExtras] = useState(structuredClone(data.extras));
  const [version, setVersion] = useState(data.version);
  const [dates, setDates] = useState(settings.closedDates.join('\n'));
  const [slots, setSlots] = useState(settings.timeSlots.join('\n'));
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const field = <K extends keyof ShopSettings>(key: K, value: ShopSettings[K]) => setSettings(current => ({ ...current, [key]: value }));
  const extraField = (id: string, update: Partial<Extra>) => setExtras(current => current.map(extra => extra.id === id ? { ...extra, ...update } : extra));
  return <>
    <div className="admin-section-heading"><div><p className="admin-kicker">РАБОТА МАСТЕРСКОЙ</p><h1>Настройки</h1><p>Изменения видны на сайте без новой сборки.</p></div></div>
    <form className="admin-settings-form" onSubmit={async event => {
      event.preventDefault(); if (busy) return; setBusy(true); setError(''); setNotice('');
      const next = { ...settings, closedDates: dates.split(/[\s,]+/).filter(Boolean), timeSlots: slots.split('\n').map(s => s.trim().replace(/\s*[-—–]\s*/g, '–')).filter(Boolean) };
      try { const result = await api<{ settings: ShopSettings; extras: Extra[]; version: number }>('admin/settings', 'PUT', { settings: next, extras, version }); setSettings(result.settings); setExtras(result.extras); setVersion(result.version); await onSaved(); setNotice('Настройки сохранены.'); }
      catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
    }}><fieldset className="admin-fieldset" disabled={busy}>
      <section className="admin-settings-section"><h2>Режим и контакты</h2><label className="admin-check"><input type="checkbox" checked={settings.demoMode} onChange={event => field('demoMode', event.target.checked)} />Учебный режим: сохранять тестовые заявки</label><p className="admin-help">В учебном режиме сайт сообщает, что доставка и оплата не выполняются. Для работы мастерской укажите её контакты и условия получения.</p><div className="admin-two-columns"><label>Телефон мастерской<input type="tel" value={settings.contactPhone} onChange={event => field('contactPhone', event.target.value)} placeholder="+7 999 123-45-67" maxLength={24} /></label><label>Telegram мастерской<input value={settings.contactTelegram} onChange={event => field('contactTelegram', event.target.value)} maxLength={32} placeholder="username без ссылки" /></label></div><label>Букет в hero<select value={settings.heroProductId} onChange={event => field('heroProductId', event.target.value)}><option value="">Первый опубликованный</option>{data.products.filter(p => p.published).map(product => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label></section>
      <section className="admin-settings-section"><h2>Доставка и самовывоз</h2><div className="admin-two-columns"><label className="admin-check"><input type="checkbox" checked={settings.courierEnabled} onChange={event => field('courierEnabled', event.target.checked)} />Доставка курьером по Перми</label><label className="admin-check"><input type="checkbox" checked={settings.pickupEnabled} onChange={event => field('pickupEnabled', event.target.checked)} />Самовывоз</label></div><div className="admin-two-columns"><label>Цена доставки, ₽<input type="number" min={0} max={50000} required value={settings.deliveryPrice} onChange={event => field('deliveryPrice', Number(event.target.value))} /></label><label>Адрес самовывоза<input maxLength={300} value={settings.pickupAddress} onChange={event => field('pickupAddress', event.target.value)} /></label></div></section>
      <section className="admin-settings-section"><h2>Расписание</h2><p className="admin-help">Все часы — по Перми (UTC+5).</p><div className="admin-days">{['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'].map((day, index) => <label key={day}><input type="checkbox" checked={settings.workingDays.includes(index + 1)} onChange={event => field('workingDays', event.target.checked ? [...settings.workingDays, index + 1] : settings.workingDays.filter(value => value !== index + 1))} /><span>{day}</span></label>)}</div><div className="admin-two-columns"><label>Закрытые даты<textarea value={dates} onChange={event => setDates(event.target.value)} rows={4} placeholder={'2026-12-31\n2027-01-01'} /><small>ГГГГ-ММ-ДД, по одной дате на строку.</small></label><label>Интервалы получения<textarea value={slots} onChange={event => setSlots(event.target.value)} rows={4} /><small>Например: 10:00–13:00. По одному интервалу на строку.</small></label></div><div className="admin-two-columns"><label>Приём на сегодня до, час<input type="number" required min={0} max={23} value={settings.sameDayCutoff} onChange={event => field('sameDayCutoff', Number(event.target.value))} /></label><label>Подготовка день в день, часов<input type="number" required min={0} max={12} value={settings.sameDayLeadHours} onChange={event => field('sameDayLeadHours', Number(event.target.value))} /></label></div><div className="admin-two-columns"><label>Заказ вперёд, дней<input type="number" required min={1} max={365} value={settings.bookingDays} onChange={event => field('bookingDays', Number(event.target.value))} /></label><label>Лимит заказов в день<input type="number" required min={1} max={500} value={settings.dailyCapacity} onChange={event => field('dailyCapacity', Number(event.target.value))} /></label></div><p className="admin-help">Заявки из каталога занимают место сразу. Индивидуальные — после подтверждения. Отмена освобождает место. Лимит относится к заказам, а не к количеству цветов на складе.</p></section>
      <section className="admin-settings-section"><h2>Дополнения</h2>{extras.map(extra => <div className="admin-extra-editor" key={extra.id}><label className="admin-check"><input type="checkbox" checked={extra.enabled} onChange={event => extraField(extra.id, { enabled: event.target.checked })} />Продавать {extra.id === 'vase' ? 'вазу' : 'открытку'}</label><div className="admin-two-columns"><label>Название<input required maxLength={60} value={extra.name} onChange={event => extraField(extra.id, { name: event.target.value })} /></label><label>Цена, ₽<input type="number" required min={0} max={50000} value={extra.price} onChange={event => extraField(extra.id, { price: Number(event.target.value) })} /></label></div><label>Описание<input maxLength={200} value={extra.description} onChange={event => extraField(extra.id, { description: event.target.value })} /></label></div>)}</section>
      <section className="admin-settings-section"><h2>Уведомления</h2><p>{data.telegramConfigured ? 'Telegram подключён.' : 'Telegram пока не подключён.'} Заказы всегда сохраняются в базе.</p><p className="admin-help">Токен бота и ID чата задаются в .env по инструкции START-WORKING-SITE.md. Контактные данные остаются в панели.</p></section>
      <button className="admin-button">{busy ? 'Сохраняем…' : 'Сохранить настройки'}</button>
    </fieldset>{error && <p className="admin-error" role="alert">{error}</p>}{notice && <p className="admin-success" role="status">{notice}</p>}</form>
  </>;
}
